import type { Metadata } from "next";
import "./globals.css";
import AppHeader from "@/components/partials/header/app-header";
import AppContent from "@/components/partials/content/app-content";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        {/*Root element*/}
        <div className={`h-screen flex flex-col`}>
          {/*App header*/}
          <AppHeader/>
          {/*App content*/}
          <AppContent>
            {children}
          </AppContent>
        </div>
      </body>
    </html>
  );
}
