"""create_product_attribute_table

Revision ID: 914b38b8fe04
Revises: 12d9eedabe64
Create Date: 2025-12-04 18:23:29.557020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '914b38b8fe04'
down_revision: Union[str, Sequence[str], None] = '12d9eedabe64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attribute_id', 'product_attribute', ['attribute_id'], unique=False)
    op.create_index('idx_product_id', 'product_attribute', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_attribute_value'), 'product_attribute', ['value'], unique=False)
    op.create_index('uq_product_attr', 'product_attribute', ['product_id', 'attribute_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_product_attr', table_name='product_attribute')
    op.drop_index(op.f('ix_product_attribute_value'), table_name='product_attribute')
    op.drop_index('idx_product_id', table_name='product_attribute')
    op.drop_index('idx_attribute_id', table_name='product_attribute')
    op.drop_table('product_attribute')
    # ### end Alembic commands ###
