"""create attributes table

Revision ID: fdaf11114d6c
Revises: 1985d2339c2b
Create Date: 2025-10-31 10:41:46.769393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fdaf11114d6c'
down_revision: Union[str, Sequence[str], None] = '1985d2339c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attribute_name', 'attributes', ['name'], unique=False)
    op.create_index(op.f('ix_attributes_name'), 'attributes', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attributes_name'), table_name='attributes')
    op.drop_index('idx_attribute_name', table_name='attributes')
    op.drop_table('attributes')
    # ### end Alembic commands ###
